testing the settings update stuff

diff --git a/.github/actions/settings/action.yml b/.github/actions/settings/action.yml
--- a/.github/actions/settings/action.yml
+++ b/.github/actions/settings/action.yml
@@ -24,11 +24,11 @@ runs:
   using: composite
   steps:
     - name: Check All Spack Major Versions in Prerelease are in Release
-      id: maj-all-pre-in-rel
+      id: spack-maj-all-pre-in-rel
       shell: bash
       run: |
         majors_only_in_prerelease=$(jq --compact-output --raw-output \
-          '.deployment.${{ inputs.target }} | (.Prerelease.spack | keys) - (.Release.spack | keys)' \
+          '.deployment.${{ inputs.target }} | (.Prerelease.spack | keys) - (.Release.spack | keys) | @sh' \
           ${{ inputs.settings-path }}
         )
 
@@ -39,11 +39,11 @@ runs:
         fi
 
     - name: Check All Spack Major Versions in Release are in Prerelease
-      id: maj-all-rel-in-pre
+      id: spack-maj-all-rel-in-pre
       shell: bash
       run: |
         majors_only_in_release=$(jq --compact-output --raw-output \
-          '.deployment.${{ inputs.target }} | (.Release.spack | keys) - (.Prerelease.spack | keys)' \
+          '.deployment.${{ inputs.target }} | (.Release.spack | keys) - (.Prerelease.spack | keys) | @sh' \
           ${{ inputs.settings-path }}
         )
 
@@ -54,7 +54,7 @@ runs:
         fi
 
     - name: Check All Spack Hash Versions are Equal
-      id: hash-all-equal
+      id: spack-hash-all-equal
       shell: bash
       run: |
         release_version_hashes=$(jq '.deployment.${{ inputs.target }}.Release.spack | to_entries' ${{ inputs.settings-path }})
@@ -63,11 +63,40 @@ runs:
         unequal_hashes_for_version=$(jq --compact-output --raw-output --null-input \
           --argjson r "$release_version_hashes" \
           --argjson p "$prerelease_version_hashes" \
-          '$r + $p | [group_by(.key)[] | select(.[0].value != .[1].value) | .[0].key]'
+          '$r + $p | [group_by(.key)[] | select(.[0].value != .[1].value) | .[0].key] | @sh'
         )
 
         if [[ "$unequal_hashes_for_version" != "" ]]; then
-          msg="Different spack hashes between Prerelease and Release for major versions ${unequal_hashes_for_version}. These should be equal to ensure equivalent builds."
+          msg="Different spack hashes between Prerelease and Release for major versions: ${unequal_hashes_for_version}. These should be equal to ensure equivalent builds."
+          echo "::${{ inputs.error-level }}::$msg"
+          echo "msg=$msg" >> $GITHUB_OUTPUT
+        fi
+
+    - name: Verify Spack Commits Exist
+      id: spack-hash-all-exist
+      env:
+        GH_TOKEN: ${{ github.token }}
+        CHECKOUT_DIR: ./spack-metadata
+      shell: bash
+      # Verify that every commit referenced actually exists on the
+      # `releases/VERSION` branch in access-nri/spack, but don't
+      # bother checking out the code.
+      run: |
+        gh repo clone access-nri/spack ${{ env.CHECKOUT_DIR }} -- --no-checkout
+
+        # Essentially, pull out all the spack 'version: hash' sections and iterate
+        jq '.deployment.${{ inputs.target }}[].spack | to_entries[] | "\(.key) \(.value)"' ${{ inputs.settings-path }} | while read -r line; do
+          eval "set -- $line"
+          version=$1
+          hash=$2
+          if ! git -C ${{ env.CHECKOUT_DIR }} merge-base --is-ancestor $hash releases/v$version; then
+            echo "::${{ inputs.error-level }}::Commit $hash does not exist on branch releases/v$version"
+            failed=true
+          fi
+        done
+
+        if [ -n $failed ]; then
+          msg="Some commits referenced do not exist in access-nri/spack. Check the workflow logs."
           echo "::${{ inputs.error-level }}::$msg"
           echo "msg=$msg" >> $GITHUB_OUTPUT
         fi
